CREATE TABLE T_ITEM (
    ITEMID INTEGER PRIMARY KEY COMMENT '商品ID',
    ORIGINALID VARCHAR(16) NOT NULL COMMENT 'オリジナルID',
    ITEMNAME VARCHAR(64) NOT NULL COMMENT '商品名',
    CATEGORY INTEGER NOT NULL COMMENT '商品カテゴリ',
    PRICE INTEGER NOT NULL COMMENT '価格',
    EXPLANATION VARCHAR(128) COMMENT '商品説明',
    IMAGENAME VARCHAR(32) COMMENT '画像ファイル名',
    CONSTRAINT CATEGORY_FK
	    FOREIGN KEY (CATEGORY)
	    REFERENCES M_CATEGORY (CATID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;