CREATE TABLE T_ORDER_LOG (
	ORDER_ID VARCHAR(36) PRIMARY KEY COMMENT 'ID',
    CUSTOMER_NAME VARCHAR(32) COMMENT '注文者名',
    ORDER_DATE TIMESTAMP COMMENT '注文日' DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=utf8;

