CREATE TABLE T_ITEM (
    ITEMID INTEGER PRIMARY KEY,
    ORIGINALID VARCHAR(16) NOT NULL,
    ITEMNAME VARCHAR(64) NOT NULL,
    CATEGORY INTEGER NOT NULL,
    PRICE INTEGER NOT NULL,
    EXPLANATION VARCHAR(128),
    IMAGENAME VARCHAR(32),
    CONSTRAINT CATEGORY_FK
	    FOREIGN KEY (CATEGORY)
	    REFERENCES M_CATEGORY (CATID)
);