CREATE TABLE T_ORDER_DETAIL (
  ID SERIAL PRIMARY KEY,
    ORDER_ID VARCHAR(36) NOT NULL,
    ORDER_ITEM_ID INT NOT NULL,
    ORDER_AMOUNT INT NOT NULL,
    CONSTRAINT ORDER_ID_FK
      FOREIGN KEY (ORDER_ID)
      REFERENCES T_ORDER_LOG (ORDER_ID),
    CONSTRAINT ITEM_ID_FK     
      FOREIGN KEY (ORDER_ITEM_ID)
      REFERENCES T_ITEM (ITEMID)
);
