CREATE TABLE T_ORDER_LOG (
	ORDER_ID VARCHAR(36) PRIMARY KEY COMMENT 'ID',
    CUSTOMER_NAME VARCHAR(32) COMMENT 'íçï∂é“ñº',
    ORDER_DATE TIMESTAMP COMMENT 'íçï∂ì˙' DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB DEFAULT CHARSET=utf8;

